blogger/config/routes.rb
# Rails.application.routes.draw do
#   # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
# end

Blogger::Application.routes.draw do

  #puts the root at the index
  root to: 'article#index'

  # should always use routes RESTful convenction
  resources :articles
end

blogger/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

blogger/app/models/article.rb
# Article is-a ApplicationRecord
class Article < ApplicationRecord
end

blogger/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

blogger/app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  # the ArticlesController class is-a Application Controller

  include ArticlesHelper
  # an action is a member of the controller
  def index
    # the index function provides the "article" on
    # the index (home) page. We want all the articles
    @article = Article.all
  end

  def show
    # this sets the article to a single article
    # by searching for the :id symbol, which is unique
    # and passed to all scope levels
    @article = Article.find(params[:id])
  end

  def new
    @article = Article.new
  end

  # include "fail" to stop process and see params
  def create
    @article = Article.new(article_params)
    @article.save

    flash.notice = "Article ''#{@article.title}' Created!"

    redirect_to article_path(@article)
  end

  def destroy
    @article = Article.find(params[:id])
    title = @article.title
    @article.destroy

    flash.notice = "Article '#{title}' Destroyed!"

    redirect_to articles_path
  end

  def edit
    @article = Article.find(params[:id])
  end

  def update
    @article = Article.find(params[:id])
    @article.update(article_params)

    flash.notice = "Article ''#{@article.title}' Updated!"

    redirect_to article_path(@article)
  end

end

blogger/app/helpers/application_helper.rb
module ApplicationHelper
end

blogger/app/helpers/articles_helper.rb
module ArticlesHelper
  def article_params
    params.require(:article).permit(:title, :body)
  end
end

blogger/app/views/articles/_form.html.erb
<%= form_for(@article) do |f| %>
<!-- create a form for the object @article, refer to the
form by the name f, and add the following elements to the
form
//-->
  <ul>
    <% @article.errors.full_messages.each do |error| %>
      <li><%= error %></li>
    <% end %>
  </ul>
  <p>
    <%= f.label :title %>
    <!-- create HTML label for a field -->
    <br/>
    <%= f.text_field :title %>
  </p>
  <p>
    <%= f.label :body %>
    <br/>
    <%= f.text_area :body %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>

blogger/app/views/articles/edit.html.erb
<h1> Edit Article </h1>

<%= render partial: 'form' %>

blogger/app/views/articles/index.html.erb
<h1>All Articles</h1>

<ul id="articles">

  <!-- need @article to be singular
   this is an embedded ruby html element
 //-->
  <% @article.each do |article| %>
    <!-- for every article (@article is an array of articles) -->
    <li>
      <!-- this symbol displays the returned ruby
      value to the DOM -->

      <%= link_to article.title, article_path(article) %>
    </li>
  <% end %>
</ul>

<!-- link_to is a function that takes the parameter
new_article_path which is a variable in the rails scope
that can be found in the routes
//-->
<%= link_to "Create a New Article", new_article_path, class: "new_article" %>

blogger/app/views/articles/new.html.erb
<h1>Create a New Article</h1>

<!-- use a partial to be efficient ( edit.html.erb is the same) -->
<%= render partial: 'form' %>

blogger/app/views/articles/show.html.erb
<h1><%= @article.title %></h1>
<p><%= @article.body %></p>
<!-- makes a link to the articles via articles_path -->
<%= link_to "<< Back to Articles List", articles_path %>
<br/>
<!-- targetted via trickle-down -->
<%= link_to "delete", article_path(@article), method: :delete,
data: {confirm: "Really delete the article?"} %>
<br/>
<%= link_to "edit", edit_article_path(@article) %>

blogger/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blogger</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <p class="flash"><%= flash.notice %></p>
    <%= yield %>
  </body>
</html>